# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI on Linux

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker Pyinstaller
      run: |
        docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller --windowed --onefile --clean -y --dist ./ --workpath /tmp tools/main.py'
        zip -r $GITHUB_WORKSPACE/main.zip $GITHUB_WORKSPACE/main.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: InfoSpider
        path: main.zip
