name: CI on Linux

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # pyinstaller 加上 -y --dist ./ --workpath /tmp 使得 exe 输出在当前目录
    - name: Docker Pyinstaller
      run: |
        docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller --onefile --clean -y --dist ./ --workpath /tmp tools/main.py'
        zip -r $GITHUB_WORKSPACE/main.zip $GITHUB_WORKSPACE/main.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: InfoSpider
        path: main.zip
